name = "Pilot Julia"
authors = ["Kleinbeck, Kevin"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
QuantumOptics = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"

[compat]
DrWatson = "2.12.0"
julia = "1.8.3"
